/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_pavle_vasiljevic_shoppinglist_JNIClass */

#ifndef _Included_com_example_pavle_vasiljevic_shoppinglist_JNIClass
#define _Included_com_example_pavle_vasiljevic_shoppinglist_JNIClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_pavle_vasiljevic_shoppinglist_JNIClass
 * Method:    increment
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_pavle_vasiljevic_shoppinglist_JNIClass_increment
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
